BUS-38 Реализовано 3 rpc запроса
crashteamdev/hermes pull request #2
Opened 2024-01-28 20:42 UTC by TrueDranik

Implemented three rpc requests.

2024-01-29 14:38 UTC, vitaxa requested changes

2024-01-29 14:38 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/grpc/CrmGrpc.java
> +        responseObserver.onNext(CreateLeadResponse.newBuilder().build());
Нельзя оставлять совсем пустой CreateLeadResponse. Надо еще добавить SuccessResponse. То есть что-то из oneOf надо заполнить, пусть даже тот же SuccessResponse будет пустой

2024-01-29 14:38 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/mapper/GrpcMapper.java
> +    private final PipelineService pipelineService;
Название Mapper вводит в заблужение. Обычно это что-то простое без бизнес-логики. У тебя тут втиснулась бизнесовая часть. Надо переименовать класс или вынести ее куда-то

2024-01-29 14:38 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/mapper/CrmMapper.java
> +@Component
А так ли нам нужно вешать аннотацию Component и делать injection в других классах? Зачем усложнять если можем использовать утилитные классы.

2024-01-29 14:38 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/model/domain/Lead.java
> +}
Должен быть пустым? Может его удалить?

2024-01-29 14:38 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/service/feign/SmsAeroClient.java
> +@FeignClient(value = "SmsAeroClient", url = "https://rns572@mail.ru:GYS6A6xfVA1-zV1TC1HJrQ8xeaPApHnI@gate.smsaero.ru/v2/")
url надо в property вынести

2024-01-29 14:38 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/service/crm/CrmServiceImpl.java
> +            "Authorization", "Bearer 0510599d43fb005883494861667b8c8c:ea6cb0d691bf40cc82f976fe8d761efe"
Этот токен не забыл в property вынести?

2024-01-29 14:38 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/service/crm/CrmServiceImpl.java
> +        log.info("Новая запись в БД:[{}]", save);
Давай переведем все логи на англ. Чтоб глаза не резало и не всплыли проблемы кодировки, вдруг.

2024-01-29 14:38 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/service/lead/LeadServiceImpl.java
> +    }
Вот тут путает. Сразу непонятно, чем отличаются saveLead от createLead. Только проваливаясь в методы можно разобраться, а такого надо избегать. Вынести saveLead и createLead в один метод CrmService. Ведь метод saveLead не должен существовать. Мы не будем создавать запись в базе без создания записи в CRM

2024-01-29 14:38 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/grpc/CrmGrpc.java
> +        String smsCode = smsService.generateSmsCode();
Смс нужно генерировать только на initialUpdateContactInfoPayload, а сейчас у тебя всегда будет генерить

2024-01-29 14:38 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/grpc/CrmGrpc.java
> +            contact = contactService.updateContact(userId, grpcMapper.map(request.getInitialUpdateContactInfoPayload()));
contact можно тут же инициализировать, зачем он выше?

2024-01-29 14:38 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/grpc/CrmGrpc.java
> +            smsService.smsSend(contact.getPhone(), smsCode);
Просто скажу, что у нас тут плохие гарантии на отправку сообщений. Вы сохранили изменения контакта, но можем зафейлить отправку смс. Так что такой подход плохой и я бы не пропускал его на прод. Но в нашем случай главное быстрее, так что переживем.

2024-01-29 14:38 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/model/domain/Crm.java
> +public class Crm {
Название какое-то абстрактное. Я даже не понимаю сразу о чем это, будто обо всем.

2024-01-29 16:48 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/grpc/CrmGrpc.java
> +        responseObserver.onNext(grpcMapper.map(contact));
Добавь чтоб тут тоже state заполнялся, тот state из которого будет понятно, что данные подтвержденные. Я в протоколе это добавил

2024-01-30 07:01 UTC, TrueDranik commented on src/main/java/dev/crashteam/hermes/grpc/CrmGrpc.java
> +        String smsCode = smsService.generateSmsCode();
Есть вопросы

2024-01-30 07:02 UTC, TrueDranik commented on src/main/java/dev/crashteam/hermes/grpc/CrmGrpc.java
> +            contact = contactService.updateContact(userId, grpcMapper.map(request.getInitialUpdateContactInfoPayload()));
Есть вопросы

2024-01-30 07:02 UTC, TrueDranik commented on src/main/java/dev/crashteam/hermes/grpc/CrmGrpc.java
> +            smsService.smsSend(contact.getPhone(), smsCode);
Может есть какие-то предложения, которые не требуют долгой реализации?

2024-01-30 10:14 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/grpc/CrmGrpc.java
> +            smsService.smsSend(contact.getPhone(), smsCode);
Неа, волшебной палочки не существует)

2024-01-30 16:06 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/model/domain/CrmDomain.java
> +public class CrmDomain {
Давай CrmUser. А то вот появится у тебя необходимость еще хранить какие-то данные из CRM и шо ты будешь делать? И название таблицы не забудь поменять

2024-01-30 17:30 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/grpc/CrmGrpc.java
> +            if (contact.getApproveCode().equals(approveCode)) {
А что если код не одинаковый? Нужно отдавать ошибку по протоколу

2024-01-30 17:54 UTC, vitaxa commented on src/main/java/dev/crashteam/hermes/grpc/CrmGrpc.java
>          Contact contact = contactService.getContact(request.getUserId());
Давай назовем UserContact

2024-01-30 18:16 UTC, vitaxa approved these changes

2024-01-30 18:17 UTC, merged